/**
 * IT Helpdesk RAG + Agent Architecture Types
 *
 * This module defines the core data contracts and schemas across the entire
 * enterprise support pipeline:
 * - Domain categories and urgency levels
 * - Routing decisions and action outcomes
 * - Ticket lifecycle states ('Pending' | 'Resolved' | 'Escalated')
 * - Knowledge base documents and vector retrieval chunks
 * - Classification, retrieval, and decision agent results
 * - KPI summary metrics and simulation parameters
 */

/**
 * Enterprise IT support service categories.
 * Centroids are computed over knowledge-base chunks in these domains.
 */
export type Category =
  | 'Hardware'
  | 'Network'
  | 'Software'
  | 'Account & Access'
  | 'Productivity'
  | 'Facility'
  | 'Others';

/**
 * Ticket urgency classification based on business impact, keyword analysis, and outage signals.
 */
export type Urgency = 'High' | 'Medium' | 'Low';

/**
 * Routed action verdicts determined by the Decision Policy Agent.
 */
export enum Action {
  /** High confidence and clear policy match; automated answer safely delivered */
  AUTO_RESOLVE = 'AUTO_RESOLVE',
  /** Retrieval similarity below confidence threshold; routed to technician queue */
  ESCALATE_LOW_CONFIDENCE = 'ESCALATE_LOW_CONFIDENCE',
  /** Physical danger, battery swelling, fire, or electrical hazards; immediate human escalation */
  ESCALATE_SAFETY = 'ESCALATE_SAFETY',
  /** High urgency outage requiring strict confidence threshold or technician verification */
  ESCALATE_HIGH_URGENCY = 'ESCALATE_HIGH_URGENCY',
}

/**
 * Lifecycle state of a support ticket within the agent console:
 * - 'Pending': Ticket queued or awaiting initial analysis / operator dispatch
 * - 'Resolved': Solution confirmed and applied (via auto-resolution or validated guide)
 * - 'Escalated': Flagged for Tier-2 engineering, field technician, or depot inspection
 */
export type TicketLifecycleState = 'Pending' | 'Resolved' | 'Escalated';

/**
 * Canonical knowledge-base document structure stored in the helpdesk database.
 */
export interface KbDocument {
  /** Unique document identifier (e.g., 'KB-ACC-001') */
  kb_id: string;
  /** Categorical domain classification */
  category: Category;
  /** High-level summary of the issue or problem statement */
  issue: string;
  /** Typical employee query or symptom description */
  question: string;
  /** Standard operating procedure or step-by-step resolution steps */
  resolution: string;
  /** Tag keywords for search indexing and categorization */
  tags: string[];
  /** Optional vendor or internal documentation URL */
  source_url?: string;
  /** Flag indicating if the document was generated via live web research */
  is_web_researched?: boolean;
  /** Timestamp when the entry was created */
  date_added?: string;
}

/**
 * Atomic text chunk derived from a KbDocument for vector embedding and retrieval.
 */
export interface KbChunk {
  /** Unique identifier for the chunk */
  chunk_id: string;
  /** Parent document identifier */
  kb_id: string;
  /** Domain category */
  category: Category;
  /** Issue title */
  issue: string;
  /** Comma-separated or space-separated tags string */
  tags: string;
  /** Sequential index within parent document */
  chunk_index: number;
  /** Cleaned text corpus used for vector embedding and TF-IDF calculation */
  text: string;
}

/**
 * Chunk returned from vector retrieval along with similarity score.
 */
export interface RetrievedChunk {
  chunk_id: string;
  kb_id: string;
  category: Category;
  issue: string;
  text: string;
  /** Cosine similarity or hybrid score in the range [0, 1] */
  similarity: number;
}

/**
 * Output of Step 1: Classification Agent.
 */
export interface ClassificationResult {
  /** Predicted category based on centroid vector distance */
  category: Category;
  /** Numerical confidence in category prediction [0, 1] */
  category_confidence: number;
  /** Urgency level determined by rule-based heuristic */
  urgency: Urgency;
  /** Specific urgency or hazard keywords matched in the query */
  matched_urgency_keywords: string[];
}

/**
 * Output of Step 4: Decision Agent policy check.
 */
export interface Decision {
  /** Routed action recommendation */
  action: Action;
  /** Human-readable explanation of why this action was selected */
  reason: string;
  /** Whether this ticket requires human agent intervention */
  requires_human: boolean;
}

/**
 * Response payload generated by the RAG engine.
 */
export interface RagResponse {
  query: string;
  answer: string;
  sources: RetrievedChunk[];
  confidence: number;
  used_llm: boolean;
}

/**
 * Complete end-to-end execution trace and resolution payload for a ticket.
 */
export interface TicketResolution {
  /** Unique tracking ID for this execution run */
  ticket_id: string;
  /** Original user prompt or ticket text */
  query: string;
  /** ISO timestamp when processing began */
  timestamp: string;
  /** Step 1 classification category */
  category: Category;
  /** Confidence in category prediction */
  category_confidence: number;
  /** Assessed urgency level */
  urgency: Urgency;
  /** Generated response or safe escalation message */
  answer: string;
  /** Retrieved knowledge-base chunks used for grounding */
  sources: RetrievedChunk[];
  /** Top-1 similarity confidence score [0, 1] */
  retrieval_confidence: number;
  /** Final policy routing action */
  action: Action;
  /** Audit reason for the chosen action */
  reason: string;
  /** Flag indicating if human technician review is necessary */
  requires_human: boolean;
  /** Total pipeline execution time in milliseconds */
  processing_time_ms: number;
  /** Whether the answer was synthesized via Gemini LLM or template fallback */
  used_llm?: boolean;
  /** Extracted equipment, operating system, and software entities */
  extracted_entities?: {
    device?: string;
    os?: string;
    application?: string;
    issue_type?: string;
  };
  /** Physical danger detection flag (battery swell, smoke, sparks) */
  safety_hazard?: boolean;
  /** Flag if server/API rate limits were active during resolution */
  rate_limited?: boolean;
  /** Informational note if fallback generation was utilized */
  fallback_note?: string;
  /** Whether the answer was grounded using live Google Search grounding */
  web_grounded?: boolean;
  /** Live external web sources cited by Gemini */
  web_sources?: Array<{ title: string; uri: string }>;
  /** Search queries executed against the Google Search tool */
  search_queries?: string[];
}

/**
 * Benchmark or historical ticket representation used in the test dataset.
 */
export interface DemoTicket {
  ticket_id: string;
  title: string;
  query: string;
  category: Category;
  ground_truth_category?: Category;
  source: 'loopback' | 'kaggle';
  priority?: string;
  status?: string;
}

/**
 * Aggregate executive performance and operational telemetry summary.
 */
export interface KpiSummary {
  total_tickets_processed: number;
  action_breakdown: Record<Action, number>;
  auto_resolve_rate: number;
  escalation_rate: number;
  category_distribution: Record<string, number>;
  urgency_distribution: Record<string, number>;
  avg_confidence: number;
  avg_processing_time_ms: number;
  classification_validation: {
    n_labeled_samples: number;
    overall_accuracy: number;
    per_category_accuracy: Record<string, number>;
  };
  business_impact_estimate: {
    assumption: string;
    tickets_auto_resolved: number;
    estimated_minutes_saved: number;
    estimated_hours_saved: number;
  };
}

/**
 * Dynamic configuration parameters for the orchestrator and policy thresholds.
 */
export interface PipelineConfig {
  /** Minimum similarity score required to auto-resolve standard tickets (default: 0.15) */
  autoResolveThreshold: number;
  /** Stricter similarity score required to auto-resolve high-urgency tickets (default: 0.30) */
  highUrgencyThreshold: number;
  /** Answer synthesis model: grounded Gemini 2.5/3 or local extractive template */
  generationMode: 'extractive' | 'gemini';
  /** Number of top chunks to retrieve from the vector index */
  topK: number;
  /** Whether to query live Google Search grounding when local KB similarity is low */
  enableWebSearch?: boolean;
}

/**
 * Pre-packaged scenario ticket for rapid interactive testing in the UI.
 */
export interface SampleQuickTicket {
  id: string;
  label: string;
  text: string;
  category: Category;
  scenarioType: 'resolve' | 'hazard' | 'urgency' | 'low_conf';
  expected: Action;
  badge: string;
  description: string;
}

